# Generated by Django 5.1.13 on 2025-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["create_date"]},
        ),
    ]
