# Generated by Django 5.1.13 on 2025-10-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_author_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_require",
            field=models.BooleanField(default=False),
        ),
    ]
